-- List the number of films per category.
-- Retrieve the store ID, city, and country for each store.
-- Calculate the total revenue generated by each store in dollars.
-- Determine the average running time of films for each category.

-- Bonus:

-- Identify the film categories with the longest average running time.
-- Display the top 10 most frequently rented movies in descending order.
-- Determine if "Academy Dinosaur" can be rented from Store 1.
-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating 
-- whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this 
-- information can be obtained using a CASE statement combined with IFNULL.
use sakila;
select count(distinct(f.film_id))  as num_films, c.name as cat_name from category as c inner join film_category as f using(category_id) group by c.name;
select s.store_id, c.city, co.country from store as s inner join address as a using(address_id) inner join city as c using(city_id) inner join country as co using(country_id); 
select s.store_id, sum(p.amount) as total_revenue from store as s inner join staff as st using(store_id) inner join payment as p using(staff_id) group by s.store_id;
select c.name as film_category, avg(f.length) as average_length from category as c inner join film_category using(category_id) inner join film as f using (film_id) group by c.name;

select c.name as film_category, avg(f.length) as average_length from category as c inner join film_category using(category_id) inner join film as f using (film_id) group by c.name order by average_length desc;
select f.title from film as f inner join inventory using(film_id) inner join rental using (inventory_id) group by f.title order by count(rental.inventory_id) desc limit 10;
select f.title,i.inventory_id,
case 
when r.return_date is null then 'available'
else 'not available'
end as availability
 from film as f inner join inventory as i using(film_id) join rental as r using(inventory_id)
where f.title like 'Academy Dinosaur' and i.store_id=1 order by r.rental_date; --  desc limit 1;

-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating 
-- whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this 
-- information can be obtained using a CASE statement combined with IFNULL.
select distinct(f.title), -- ifnull(i.inventory_id,'not stocked'),
case 
when inventory_id in (select inventory_id from sakila.rental where return_date is null) then 'available'
when isnull(inventory_id) then 'not stocked'
else 'not available'
end as availability
 from film as f left join inventory as i using(film_id) join rental as r using(inventory_id);

 

 
 