-- List the number of films per category.
-- Retrieve the store ID, city, and country for each store.
-- Calculate the total revenue generated by each store in dollars.
-- Determine the average running time of films for each category.

-- Bonus:

-- Identify the film categories with the longest average running time.
-- Display the top 10 most frequently rented movies in descending order.
-- Determine if "Academy Dinosaur" can be rented from Store 1.
-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating 
-- whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this 
-- information can be obtained using a CASE statement combined with IFNULL.
USE sakila;

SELECT 
	count(distinct(f.film_id))  as num_films, 
    c.name as cat_name 
FROM category as c 
JOIN film_category as f 
	using(category_id) 
GROUP BY c.name;

SELECT 
	s.store_id, 
    c.city, 
    co.country 
FROM store as s 
INNER JOIN address as a 
	USING(address_id) 
INNER JOIN city as c 
	USING(city_id) 
INNER JOIN country as co 
	USING(country_id); 

SELECT
	s.store_id, 
    sum(p.amount) as total_revenue 
FROM store as s 
INNER JOIN staff as st 
	USING(store_id) 
INNER JOIN payment as p 
	USING(staff_id) 
GROUP BY s.store_id;

SELECT 
	c.name as film_category, 
    avg(f.length) as average_length 
FROM category as c 
INNER JOIN film_category 
	USING(category_id) 
INNER JOIN film as f 
	USING (film_id) 
GROUP BY c.name;

SELECT 
	c.name as film_category, 
	avg(f.length) as average_length 
FROM category as c 
INNER JOIN film_category 
	USING(category_id) 
INNER JOIN film as f 
	USING (film_id) 
GROUP BY c.name 
ORDER BY average_length desc;

SELECT 
	f.title 
FROM film as f 
JOIN inventory 
	USING(film_id) 
JOIN rental 
	USING (inventory_id) 
GROUP BY f.title 
ORDER BY count(rental.inventory_id) DESC 
LIMIT 10;

SELECT 
	f.title,
    i.inventory_id,
CASE 
WHEN r.return_date IS NULL THEN 'available'
ELSE 'not available'
END AS availability
FROM film as f 
JOIN inventory as i 
	USING(film_id) 
JOIN rental as r 
	USING(inventory_id)
WHERE f.title LIKE 'Academy Dinosaur' AND i.store_id=1 
ORDER BY r.rental_date; --  desc limit 1;

-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating 
-- whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this 
-- information can be obtained using a CASE statement combined with IFNULL.
SELECT DISTINCT f.title, -- ifnull(i.inventory_id,'not stocked'),
CASE 
WHEN inventory_id IN (
	SELECT inventory_id 
    FROM sakila.rental 
    WHERE return_date IS NULL) THEN 'available'
WHEN isnull(inventory_id) THEN 'not stocked'
ELSE 'not available'
END AS availability
FROM film as f 
LEFT JOIN inventory as i 
	USING(film_id) 
JOIN rental as r 
	USING(inventory_id);

 

 
 